spring:

  application:
    name: sample-ddd

  h2:
    console:
      enabled: true
      
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:sample;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    username: sa
    password:
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:      
      hibernate:
        ddl-auto: none
        format_sql: true

